[package]
name = "purrgress"
version = "0.5.0"
edition = "2024"

documentation = "https://docs.rs"

description = "An ultra-fast, ergonomic DOD stage manager and async sequencer combining zero-cost performance with total runtime dynamism."

license = "MIT"

repository = "https://github.com/Honami333/purrgress"

keywords = ["state-machine", "async", "zero-cost", "sequencer", "lock-free"]

categories = ["asynchronous", "concurrency", "data-structures", "rust-patterns"]

exclude = [
    ".github/*",
    "target/*",
]

[dependencies]
anyhow = "1.0.103"
bevy_ecs  = { version = "0.18", optional = true, default-features = false }
petgraph = { version = "0.8.3", optional = true }
purrgress-macros = { version = "0.5.0", path = "./purrgress-macros", optional = true  }
cursorvec = { version = "0.2.0", optional = true }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time"], optional = true }
rkyv = { version = "0.8.18", features = ["bytes-1"], optional = true }
bytes = { version = "1.12.1", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }

[features]
default = []
bevy_ecs = ["dep:bevy_ecs"]
train = ["purrgress-macros/train", "macros", "cursorvec"]
cursorvec = ["dep:cursorvec"]
dispatcher = ["purrgress-macros/dispatcher", "rkyv", "train", "dep:tokio", "dep:bytes"]
animator = ["purrgress-macros/animator", "scrap", "macros", "dep:petgraph"]
scrap = ["purrgress-macros/scrap", "macros", "dep:petgraph"]
rkyv = ["dep:rkyv"]
serde = ["dep:serde"]
macros = ["dep:purrgress-macros"]

[[example]]
name = "basic_test"
path = "examples/basic_test.rs"
required-features = ["scrap"]

[[example]]
name = "pandemonium_fps_test"
path = "examples/pandemonium_fps_test.rs"
required-features = ["animator", "scrap"]

[[example]]
name = "work_under_tets"
path = "examples/work_under_tets.rs"
required-features = ["scrap"]

[[example]]
name = "purr_train"
path = "examples/purr_train.rs"
required-features = ["train"]

[[example]]
name = "purr_dispatcher"
path = "examples/purr_dispatcher.rs"
required-features = ["dispatcher"]
